server:
  port: 8765

spring:
  application:
    name: gr-conf-swagger-aggregator

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

#springdoc:
#  swagger-ui:
#    urls:
#      # Les URLs seront configur√©es dynamiquement
#    disable-swagger-default-url: true
#  api-docs:
#    enabled: true


#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
#    urls: []
#  api-docs:
#    path: /v3/api-docs
#    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true